CREATE DATABASE efcore_dotnet;
CREATE USER efcore_user WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE efcore_dotnet TO efcore_user;
\c efcore_dotnet
GRANT ALL ON SCHEMA public TO efcore_user;



CREATE TABLE "public"."room" (
    "room_id" integer DEFAULT nextval('room_room_id_seq') NOT NULL,
    "room_name" character varying NOT NULL,
    "some_string" character varying(80) DEFAULT '' NOT NULL,
    CONSTRAINT "room_pkey" PRIMARY KEY ("room_id")
) WITH (oids = false);

COMMENT ON COLUMN "public"."room"."room_id" IS 'this is the room id';

INSERT INTO "room" ("room_id", "room_name", "some_string") VALUES
(1,	'zimmer',	'');






-- CREATE TABLE room (
--     roomId          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     some_number     integer NOT NULL,
--     some_string     varchar(40) NOT NULL,
--     date_created    timestamp without time zone default (now() at time zone 'utc') NOT NULL
-- );
